version: "3.9"

services:
  mock-api-server:
    image: ghcr.io/elvinyao/mock-custom-api-server:latest
    container_name: mock-api-server
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["/app/mock-api-server", "-config", "/app/conf/config.yaml"]
    volumes:
      - ./conf:/app/conf:ro
      - ./recorded:/app/recorded
      - ./logs:/app/logs
